### ISSUE TITLE
Error with parsing

### ISSUE THREAD

**Issue by Pureaznangel** [turhany/DynamicRouteParameterParser#1]
By using value:
var sampleUrl = "https://shopee.com.my/abc-i.254073001.10836392594";
var routeTemplate = "https://shopee.com.my/abc-i.{shop}.{item}";

I got only: 
Parse Result
--------------
Key - Value - Type
--------------
shop - 254073001.10836392594 - Route
item -  - Route

Instead of:
shop - 254073001 - Route
item -  10836392594 - Route

How could I correct this wrong, please help me.

Thanks,

**Comment by turhany** [comment]
@Pureaznangel hi,

This is because you url contains "."(point) and it is special char for regex flow.

I fixed that problem and released new version.

Thank you for your interest.

**Comment by Pureaznangel** [comment]
Thank you for your response,

Your code is very useful and helps us a lot.

Regards,

**Comment by Pureaznangel** [comment]
Please add support for .NET Framework 4.7.2 so I could install it directly from Nuget for my projects in future.

Thanks!
